apiVersion: v1
kind: BuildConfig
metadata:
  name: bluegreen-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/tariq-islam/bluegreen
      ref: ocp33-pipeline-ti
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  output:
    to:
      kind: ImageStreamTag
      name: 'bluegreen:latest'
status:

