apiVersion: v1
kind: BuildConfig
metadata:
  name: bluegreen-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: <your fork here>
      ref: <your branch here, if applicable>
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  output:
    to:
      kind: ImageStreamTag
      name: 'bluegreen:latest'
status:

